# General Parameters
checkpoint:             # set the checkpoint from where to continue, leave empty to start from scratch
log_name: training_binary_ensemble_plus.log  # name of the file with training info
gpu:                    # index of a GPU, if available
output_directory: dev_experiments/ImageNet  # the directory where to write the model file
parallel: false

model_path: "{}/{}_{}_{}.pth" #for those which use pretrained models

# Data Parameters
data:
  dataset: ImageNet  # Dataset to use
  imagenet_path: /local/scratch/datasets/ImageNet/ILSVRC2012/ # ILSVRC2012 path
  train_file: protocols/p{}_train.csv        # relative to data directory
  val_file:   protocols/p{}_val.csv          # relative to data directory
  test_file:  protocols/p{}_test.csv         # relative to data directory

unknown_for_training: False # If True, the unknown class is included in the training set
unknown_in_both: False      # If True, the model is forced to learn 0.5 output for the unknown class
remove_negative: False      # If True, the negative class is removed from the logits

# Common parameters
seed: 42        # Common seed across all source of randomness
batch_size: 32  # If distributed training the batch size is multiplied by the number of gpus
epochs: 120     # Number of epochs to train.
workers: 0      # Dataloader number of workers
patience: 0    # Number of epochs to wait before stopping the training. 0 means no early stopping

# loss parameters
loss:
  type: bce  # either {entropic, softmax, garbage, bce}
  # Entropic Parameters
  w: 1.

# Optimizer Parameters
opt:
  type: adam  # Two options: {adam, sgd}
  lr: 1.e-3   # Initial learning rate
  decay: 0    # Number of epochs to wait for each learning rate reduction. 0 means no decay
  gamma: 1    # Factor to reduce the learning rate

# Algorithm parameters
algorithm:
  type: binary_ensemble_combined_imagenet  # Algorithm to use
  model: resnet50Plus # resnet50Plus or leave empty for resnet50
  sets: random # Either random or hamming, selects the way to create the class sets
  num_models: 40
